version: "3.7"

services:
  worker:
    build:
      context: ./worker
    ports:
      - "4000:4000"

  server:
    build:
      context: ./server
    ports:
      - "4001:4001"
    
  nginx_heply:
    ports:
      - "80:80"    
    build:
      context: ./frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d
