version: "3.7"

services:
  worker:
    image: haply-front:latest
    ports:
      - "4000:4000"

  server:
    image: haply-server:latest
    ports:
      - "4001:4001"
    
  nginx_heply:
    image: haply-worker:latest
    ports:
      - "80:80"    
    volumes:
      - ./nginx:/etc/nginx/conf.d
